#!/bin/sh
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/extras/install-podman | sh -s -- --prefix ~/.local
echo "export PATH=$HOME/.local/bin:$HOME/.local/podman/bin:$PATH" >> $HOME/.bashrc
echo "PATH=\"$PATH:$HOME/.local/podman/bin\"" >> $HOME/.distroboxrc
. $HOME/.bashrc
. $HOME/.distroboxrc
distrobox create --yes --no-entry --image registry.fedoraproject.org/fedora-toolbox:latest --name fedora --pre-init-hooks "dnf copr enable atim/lazygit -y" --additional-packages "neovim python3-neovim lsd bat alacritty zsh stow gcc htop lazygit alacritty util-linux-user" --init-hooks "chsh -s /bin/zsh"
distrobox enter fedora -- distrobox-export --app alacritty
