#!/bin/sh
sudo dnf install gnome-tweaks gnome-shell-extension-no-overview gnome-shell-extension-appindicator -y
sudo dnf remove gnome-maps gnome-logs gnome-font-viewer gnome-photos gnome-tour gnome-weather gnome-calendar gnome-characters gnome-clocks gnome-contacts totem cheese simple-scan gnome-abrt rhythmbox gnome-connections -y

gsettings set org.gnome.mutter check-alive-timeout 60000
