#!/bin/sh
# DNF
echo "Starting DNF setup:\n"
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf groupupdate core
sudo dnf upgrade -y
sudo dnf swap ffmpeg-free ffmpeg --allowerasing
sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
sudo dnf groupupdate sound-and-video
sudo dnf install neovim python3-neovim lsd bat alacritty zsh stow htop util-linux-user steam-devices f36-backgrounds-gnome gnome-shell-extension-no-overview gnome-shell-extension-appindicator
sudo dnf remove firefox
sudo dnf groupinstall "C Development Tools and Libraries"
chsh -s /usr/bin/zsh

# Dotfiles
echo "Starting dotfiles setup:\n"
git clone https://github.com/Stargazer3240/dotfiles.git ~/.dotfiles
cd ~/.dotfiles
rm .git -rf
stow git alacritty zsh

# Flatpak
echo "Starting Flatpak setup:\n"
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
flatpak remote-delete fedora
flatpak uninstall --unused --delete-data
flatpak install \
	org.mozilla.firefox \
	org.libreoffice.LibreOffice \
	org.gimp.GIMP \
	it.mijorus.gearlever \
	io.gitlab.librewolf-community \
	io.github.celluloid_player.Celluloid \
	io.freetubeapp.FreeTube \
	com.valvesoftware.Steam \
	com.mattjakeman.ExtensionManager \
	com.github.tchx84.Flatseal \
	com.github.Eloston.UngoogledChromium \
	com.github.wwmm.easyeffects \
	gg.minion.Minion \

systemctl reboot
